name: Compilar APK Rapido

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Dependências Mínimas
      run: |
        sudo apt-get update
        sudo apt-get install -y git ccache openjdk-17-jdk python3-pip
        pip install --upgrade pip setuptools buildozer cython

    - name: Compilar APK
      run: |
        yes | buildozer android debug

    - name: Enviar APK para Download
      uses: actions/upload-artifact@v4
      with:
        name: timoteo-sms-apk
        path: bin/*.apk
        
